/** @type {import('next').NextConfig} */

const nextConfig = {
  env: {
    NEXT_PUBLIC_APPWRITE_URL: process.env.NEXT_PUBLIC_APPWRITE_URL,
    NEXT_PUBLIC_APPWRITE_PROJECT_ID:
      process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID,
    NEXT_PUBLIC_APPWRITE_DB_ID: process.env.NEXT_PUBLIC_APPWRITE_DB_ID,
    NEXT_PUBLIC_APPWRITE_BLOGS_ID: process.env.NEXT_PUBLIC_APPWRITE_BLOGS_ID,
    NEXT_PUBLIC_APPWRITE_BLOGS_STORAGE_ID:
      process.env.NEXT_PUBLIC_APPWRITE_BLOGS_STORAGE_ID,
    NEXT_PUBLIC_APPWRITE_TESTIMONIALS_ID:
      process.env.NEXT_PUBLIC_APPWRITE_TESTIMONIALS_ID,
    NEXT_PUBLIC_APPWRITE_TESTIMONIALS_STORAGE_ID:
      process.env.NEXT_PUBLIC_APPWRITE_TESTIMONIALS_STORAGE_ID,
    NEXT_PUBLIC_APPWRITE_INSTITUTIONS_ID:
      process.env.NEXT_PUBLIC_APPWRITE_INSTITUTIONS_ID,
    NEXT_PUBLIC_APPWRITE_INSTITUTIONS_STORAGE_ID:
      process.env.NEXT_PUBLIC_APPWRITE_INSTITUTIONS_STORAGE_ID,
  },
};

export default nextConfig;

module.exports = {
  images: {
    domains: ["cloud.appwrite.io"],
  },
};
